require('dotenv').config();
module.exports=
    {
        MongoDB:process.env.MONGODB,
        AWSAccessID:process.env.AWSACCESSID,
        AWSSecretKey:process.env.AWSSECRETKET,
        StripePublishableKey:process.env.STRIPEPUBLISHABLEKEY,
        StripeSecreatKey:process.env.STRIPESECREATKEY
    }
