const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const carSchema={
    owner:{
        type:Schema.Types.ObjectId,
        ref:'User'
    },
    make:{
        type:String
    },
    model:{
        type:String
    },
    year:{
        type:Number
    },
    priceperhour:{
        type:Number
    },
    priceperweek:{
        type:Number
    },
    location:[{
        address:{
            type:String
        },
        city:{
            type:String
        },
        state:{
            type:String
        },
        lat:{
            type:Number
        },
        lng:{
            type:Number
        }
    }],
    date:{
        type:Date,
        default:Date.now
    }
}
module.exports=mongoose.model('car',carSchema);