const mongoose=require('mongoose');
const Schema=mongoose.Schema;
const userSchema=new Schema({
    facebook:{
        type:String
    },
    google:{
        type:String
    },
    firstname:{
        type:String
    },
    lastname:{
        type:String
    },
    image:{
        type:String,
        default:'/img/imglogo.png'
    },
    email:{
        type:String
    },
    password:{
        type:String
    },
    date:{
        type:Date,
        default:Date.now
    },
    phone:{
        type:String
    },
    online:{
        type:Boolean,
        default:false
    },
    chat:[{
        sender:{
            type:Schema.Types.ObjectId,
            ref:'User'
        },
    }]
});
module.exports=mongoose.model('User',userSchema);